[package]
name = "ugbe-sdl2"
version = "0.1.0"
edition = "2021"
authors = ["Quentin BUATHIER <quentinbuathier@gmail.com>"]
license = "MIT"

[dependencies]
sdl2 = { version = "0.35.2", features = ["bundled", "static-link"] }
ugbe = { version = "=0.1.0", path = "../ugbe" }
